# SPDX-FileCopyrightText: Stone Tickle <lattis@mochiro.moe>
# SPDX-FileCopyrightText: Vincent Torri <vtorri@outlook.fr>
# SPDX-License-Identifier: GPL-3.0-only

name: msys2

on:
  push:
    branches:
      - master
      - '[0-9]+.[0-9]+'
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - { icon: 'â¬›', sys: mingw32, runs-on: 'windows-latest' }
          - { icon: 'ðŸŸ¦', sys: mingw64, runs-on: 'windows-latest' }
          - { icon: 'ðŸŸ¨', sys: ucrt64, runs-on: 'windows-latest' }
          - { icon: 'ðŸŸ§', sys: clang64, runs-on: 'windows-latest' }
          - { icon: 'ðŸŸ©', sys: clangarm64, runs-on: 'windows-11-arm' }
    name: ðŸš§${{ matrix.icon }} ${{ matrix.sys }}
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: 'ðŸ§° Checkout'
      uses: actions/checkout@master
    - name: '${{ matrix.icon }} Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
        update: true
        install: base-devel git pacboy
    - name: '${{ matrix.icon }} Dependencies'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
        update: true
        pacboy: >-
          toolchain:p
          pkgconf:p
          curl:p
          libarchive:p
    - name: 'ðŸš§ Build TOOL'
      run: |
        CC="gcc -std=c99"  ./bootstrap.sh build
        CC="gcc -std=c99" ./build/muon-bootstrap.exe setup build
        build/muon-bootstrap.exe -C build samu
    - name: 'ðŸ”¬ Tests'
      run: |
        ./build/muon.exe -C build test -v -ddots || true
